## Section 10, class 98 - Regularization

#### Standardization:   $X_{standardized}=\frac{X-\mu}{\sigma}$             ($\mu=0, \sigma=1$)
#### Normalization:     $X_{normalized}=\frac{X-X_{min}}{X_{max}-X_{min}}$  ($X_{normalized} \in [0;1]$)

## Cross-validation

#### Use all the data for training and evaluation
- train on all the data
- evaluate on all the data

#### Steps for cross-validation
1. get all the original data
2. split the data into K equal parts
3. 1/K is left as test set
4. train model and get error metric for split
5. keep repeating for all possible splits
6. the average error is the expected performance

* Computationally expensive: choose $K=10\%$

## Section 10, class 101 - Exercise

#### Import the relevant libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#### Import data

In [2]:
df = pd.read_csv('Advertising.csv')

In [3]:
data = df.copy()

In [5]:
X = data.drop('sales', axis=1)
y = data['sales']

#### Create the polynomial

In [6]:
from sklearn.preprocessing import PolynomialFeatures

In [7]:
polynomial_converter = PolynomialFeatures(degree=3, include_bias=False)

In [8]:
poly_features = polynomial_converter.fit_transform(X)

In [9]:
poly_features.shape

(200, 19)

#### Train-test split

In [10]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [14]:
X_train.shape

(140, 19)

#### Scale the data

In [20]:
from sklearn.preprocessing import StandardScaler

In [21]:
scaler = StandardScaler()

In [22]:
scaler.fit(X_train)

StandardScaler()

In [23]:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [25]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

### Ridge regression

In [26]:
from sklearn.linear_model import Ridge

In [27]:
ridge_model = Ridge(alpha=10)

In [28]:
ridge_model.fit(X_train, y_train)

Ridge(alpha=10)

In [29]:
test_predictions_ridge = ridge_model.predict(X_test)

In [30]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [34]:
MAE = mean_absolute_error(y_test, test_predictions_ridge)
MAE

0.5774404204714167

In [35]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions_ridge))
RMSE

0.894638646131965

#### Cross-validation of the data provided

In [36]:
from sklearn.linear_model import RidgeCV

In [44]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0), scoring='neg_mean_absolute_error')

In [45]:
ridge_cv_model.fit(X_train, y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_absolute_error')

##### Finds the best alpha

In [46]:
ridge_cv_model.alpha_

0.1

##### What was used to measure the best performing alpha

In [47]:
from sklearn.metrics import SCORERS

In [48]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_wei

In [50]:
test_predictions_ridge = ridge_cv_model.predict(X_test)

In [54]:
MAE = mean_absolute_error(y_test, test_predictions_ridge)
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions_ridge))

In [55]:
MAE

0.4273774884351013

In [56]:
RMSE

0.6180719926948981

In [57]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

### LASSO: Least Absolute Shrinkage and Selection Operator

In [59]:
from sklearn.linear_model import LassoCV

In [95]:
lasso_cv_model = LassoCV(eps=0.001, n_alphas=100, cv=5, max_iter=1e6)

In [96]:
lasso_cv_model.fit(X_train, y_train)

LassoCV(cv=5, max_iter=1000000.0)

In [97]:
lasso_cv_model.alpha_

0.004943070909225833

In [98]:
test_predictions_lasso = lasso_cv_model.predict(X_test)

In [99]:
MAE = mean_absolute_error(y_test, test_predictions_lasso)
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions_lasso))

In [100]:
MAE

0.4335034618590078

In [101]:
RMSE

0.6063140748984043

In [77]:
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

### Combining Ridge and Lasso Regressions - Elastic Net

In [78]:
from sklearn.linear_model import ElasticNetCV

In [79]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7, .9, .95, .99, 1], eps=0.001, n_alphas=100, max_iter=1000000)

In [80]:
elastic_model.fit(X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [81]:
elastic_model.l1_ratio_

1.0

This result shows that the Ridge model was disconsidered completely in regards to the Lasso model

In [82]:
elastic_model.alpha_

0.004943070909225833

In [83]:
lasso_cv_model.alpha_

0.4943070909225832

In [84]:
test_predictions_elastic = elastic_model.predict(X_test)

In [86]:
MAE = mean_absolute_error(y_test, test_predictions_elastic)

In [87]:
MAE

0.4335034618590078